import re
from typing import Dict, Any

class MQL5Generator:
    """Generates clean, compilable, institutional-grade MQL5 Expert Advisors."""

    @staticmethod
    def generate(strategy_spec: Dict[str, Any]) -> str:
        strategy_type = strategy_spec.get("strategy_type", "")
        if strategy_type == "orb_first_candle" or strategy_spec.get("is_first_candle_orb"):
            return MQL5Generator.generate_orb_first_candle(strategy_spec)

        name = strategy_spec.get("name", "AI_Generated_Strategy")
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
        description = strategy_spec.get("description", "Automated strategy generated by Trading Strategy Studio")
        
        lot_size = strategy_spec.get("default_lot", 0.01)
        sl_points = strategy_spec.get("stop_loss_points", 300)
        tp_points = strategy_spec.get("take_profit_points", 600)
        be_pips = strategy_spec.get("breakeven_pips", 15)
        trailing_pips = strategy_spec.get("trailing_stop_pips", 12)
        magic_number = strategy_spec.get("magic_number", 789101)

        start_hour = strategy_spec.get("start_hour", 13)
        start_min = strategy_spec.get("start_minute", 30)
        end_hour = strategy_spec.get("end_hour", 20)
        end_min = strategy_spec.get("end_minute", 0)
        use_time_filter = strategy_spec.get("use_time_filter", True)
        max_spread = strategy_spec.get("max_spread_points", 35)
        
        indicators = strategy_spec.get("indicators", [])
        entry_buy_logic = strategy_spec.get("entry_buy_code", "false")
        entry_sell_logic = strategy_spec.get("entry_sell_code", "false")
        exit_buy_logic = strategy_spec.get("exit_buy_code", "false")
        exit_sell_logic = strategy_spec.get("exit_sell_code", "false")
        custom_inputs = strategy_spec.get("custom_inputs", [])

        # Build Input variables
        inputs_code = []
        inputs_code.append(f'input group "=== Risk and Order Settings ==="')
        inputs_code.append(f'input double InpLotSize        = {lot_size};       // Lot Size')
        inputs_code.append(f'input int    InpStopLossPips   = {sl_points // 10};       // Stop Loss (Pips)')
        inputs_code.append(f'input int    InpTakeProfitPips = {tp_points // 10};      // Take Profit (Pips)')
        inputs_code.append(f'input int    InpBreakEvenPips  = {be_pips};       // Break-Even Trigger (Pips, 0=Off)')
        inputs_code.append(f'input int    InpTrailingPips   = {trailing_pips};       // Trailing Stop (Pips, 0=Off)')
        inputs_code.append(f'input ulong  InpMagicNumber    = {magic_number};   // Magic Number')
        inputs_code.append(f'input int    InpSlippage       = 10;               // Slippage Points')

        inputs_code.append(f'input group "=== Session and Operating Hours ==="')
        inputs_code.append(f'input bool   InpUseTimeFilter  = {"true" if use_time_filter else "false"};       // Enable Trading Session Filter')
        inputs_code.append(f'input int    InpStartHour      = {start_hour};       // Session Start Hour (Server Time)')
        inputs_code.append(f'input int    InpStartMinute    = {start_min};       // Session Start Minute')
        inputs_code.append(f'input int    InpEndHour        = {end_hour};       // Session End Hour')
        inputs_code.append(f'input int    InpEndMinute      = {end_min};       // Session End Minute')
        inputs_code.append(f'input bool   InpFilterFriday   = true;       // Avoid Friday Late Afternoon Trading')

        inputs_code.append(f'input group "=== Spread and Safety Filter ==="')
        inputs_code.append(f'input int    InpMaxSpreadPoints= {max_spread};       // Max Allowed Spread (Points, 0=Off)')
        
        standard_input_names = {
            "InpLotSize", "InpStopLossPips", "InpTakeProfitPips", "InpBreakEvenPips", "InpTrailingPips",
            "InpMagicNumber", "InpSlippage", "InpUseTimeFilter", "InpStartHour", "InpStartMinute",
            "InpEndHour", "InpEndMinute", "InpFilterFriday", "InpMaxSpreadPoints"
        }
        
        filtered_custom = [inp for inp in custom_inputs if inp.get("name") not in standard_input_names]
        if filtered_custom:
            inputs_code.append(f'input group "=== Strategy Parameters ==="')
            for inp in filtered_custom:
                inputs_code.append(f"input {inp['type']} {inp['name']} = {inp['default']}; // {inp.get('comment', inp['name'])}")

        # Build indicator handle declarations and init code
        handle_decls = []
        handle_inits = []
        handle_releases = []
        copy_buffers = []

        for ind in indicators:
            h_var = ind["handle_var"]
            b_var = ind["buffer_var"]
            init_call = ind["init_call"]
            
            handle_decls.append(f"int {h_var} = INVALID_HANDLE;")
            handle_decls.append(f"double {b_var}[];")
            
            handle_inits.append(f"   {h_var} = {init_call};")
            handle_inits.append(f"   if({h_var} == INVALID_HANDLE)")
            handle_inits.append(f"   {{\n      Print(\"Error creating indicator {h_var}: \", GetLastError());\n      return INIT_FAILED;\n   }}")
            handle_inits.append(f"   ArraySetAsSeries({b_var}, true);")
            
            handle_releases.append(f"   if({h_var} != INVALID_HANDLE) IndicatorRelease({h_var});")
            
            copy_buffers.append(f"   if(CopyBuffer({h_var}, 0, 1, 3, {b_var}) <= 0) return;")

        inputs_str = "\n".join(inputs_code)
        handle_decls_str = "\n".join(handle_decls)
        handle_inits_str = "\n".join(handle_inits)
        handle_releases_str = "\n".join(handle_releases)
        copy_buffers_str = "\n".join(copy_buffers)

        mql5_code = f"""//+------------------------------------------------------------------+
//|                                     {safe_name}.mq5 |
//|                                  Trading Strategy Studio (AI)    |
//+------------------------------------------------------------------+
#property copyright "Trading Strategy Studio"
#property link      "https://github.com/enfoc/trading-strategy-studio"
#property version   "1.00"
#property description "{description}"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>

//--- Input parameters
{inputs_str}

//--- Global Objects
CTrade         m_trade;
CPositionInfo  m_position;
datetime       m_last_bar_time = 0;

//--- Indicators Handles and Buffers
{handle_decls_str}

//+------------------------------------------------------------------+
//| Autonomous Mathematical Indicators Library (Zero External Files) |
//+------------------------------------------------------------------+
// 1. SuperTrend Engine
void CalculateSuperTrend(int atr_period, double multiplier, double &st_upper, double &st_lower, int &st_trend)
{{
   int lib_atr = iATR(_Symbol, _Period, atr_period);
   if(lib_atr == INVALID_HANDLE) return;
   double atr_buf[];
   ArraySetAsSeries(atr_buf, true);
   if(CopyBuffer(lib_atr, 0, 1, 2, atr_buf) <= 0) {{ IndicatorRelease(lib_atr); return; }}
   
   MqlRates r[];
   ArraySetAsSeries(r, true);
   if(CopyRates(_Symbol, _Period, 1, 2, r) <= 0) {{ IndicatorRelease(lib_atr); return; }}
   
   double hl2 = (r[0].high + r[0].low) / 2.0;
   double basic_upper = hl2 + (multiplier * atr_buf[0]);
   double basic_lower = hl2 - (multiplier * atr_buf[0]);
   
   st_upper = basic_upper;
   st_lower = basic_lower;
   
   if(r[0].close > st_upper) st_trend = 1;
   else if(r[0].close < st_lower) st_trend = -1;
   else st_trend = (r[1].close > r[1].open) ? 1 : -1;
   
   IndicatorRelease(lib_atr);
}}

// 2. HalfTrend / Volatility Channel Engine
void CalculateHalfTrend(int amplitude, int channel_dev, double &ht_trend_line, int &ht_direction)
{{
   int lib_atr_ht = iATR(_Symbol, _Period, 100);
   if(lib_atr_ht == INVALID_HANDLE) return;
   double atr_buf[];
   ArraySetAsSeries(atr_buf, true);
   if(CopyBuffer(lib_atr_ht, 0, 1, 1, atr_buf) <= 0) {{ IndicatorRelease(lib_atr_ht); return; }}
   
   MqlRates r[];
   ArraySetAsSeries(r, true);
   if(CopyRates(_Symbol, _Period, 1, amplitude + 1, r) <= 0) {{ IndicatorRelease(lib_atr_ht); return; }}
   
   double highest = r[0].high;
   double lowest  = r[0].low;
   for(int i = 0; i < amplitude; i++)
   {{
      if(r[i].high > highest) highest = r[i].high;
      if(r[i].low < lowest) lowest = r[i].low;
   }}
   
   double dev = (channel_dev * atr_buf[0]) / 2.0;
   if(r[0].close > (lowest + dev))
   {{
      ht_direction = 1;
      ht_trend_line = lowest + dev;
   }}
   else if(r[0].close < (highest - dev))
   {{
      ht_direction = -1;
      ht_trend_line = highest - dev;
   }}
   else
   {{
      ht_direction = 0;
      ht_trend_line = (highest + lowest) / 2.0;
   }}
   IndicatorRelease(lib_atr_ht);
}}

// 3. Quantitative Qualitative Estimation (QQE) Engine
void CalculateQQE(int rsi_period, int sf, double wilders_factor, double &qqe_line, double &qqe_signal)
{{
   int h_rsi = iRSI(_Symbol, _Period, rsi_period, PRICE_CLOSE);
   if(h_rsi == INVALID_HANDLE) return;
   double rsi_buf[];
   ArraySetAsSeries(rsi_buf, true);
   if(CopyBuffer(h_rsi, 0, 1, sf + 2, rsi_buf) <= 0) {{ IndicatorRelease(h_rsi); return; }}
   
   double rsi_sum = 0;
   for(int i = 0; i < sf; i++) rsi_sum += rsi_buf[i];
   double smoothed_rsi = rsi_sum / (double)sf;
   
   double delta = MathAbs(rsi_buf[0] - rsi_buf[1]);
   double dar = delta * wilders_factor;
   
   qqe_line = smoothed_rsi;
   if(smoothed_rsi > 50.0) qqe_signal = smoothed_rsi - dar;
   else qqe_signal = smoothed_rsi + dar;
   
   IndicatorRelease(h_rsi);
}}

// 4. Institutional SMC Fair Value Gap (FVG) Scanner
bool DetectFairValueGap(int bar_index, bool &is_bullish_fvg, double &fvg_top, double &fvg_bottom)
{{
   MqlRates r[];
   ArraySetAsSeries(r, true);
   if(CopyRates(_Symbol, _Period, bar_index, 4, r) < 4) return false;
   
   // Bullish FVG: Low of candle 0 > High of candle 2
   if(r[0].low > r[2].high)
   {{
      is_bullish_fvg = true;
      fvg_top = r[0].low;
      fvg_bottom = r[2].high;
      return true;
   }}
   // Bearish FVG: High of candle 0 < Low of candle 2
   else if(r[0].high < r[2].low)
   {{
      is_bullish_fvg = false;
      fvg_top = r[2].low;
      fvg_bottom = r[0].high;
      return true;
   }}
   return false;
}}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{{
   m_trade.SetExpertMagicNumber(InpMagicNumber);
   m_trade.SetDeviationInPoints(InpSlippage);
   m_trade.SetTypeFillingBySymbol(_Symbol);

{handle_inits_str}

   MqlDateTime dt_init;
   TimeToStruct(TimeCurrent(), dt_init);
   PrintFormat("Servidor MT5 conectado. Hora actual del servidor: %02d:%02d. Horario operativo programado: %02d:%02d a %02d:%02d (Hora de Servidor MT5).",
      dt_init.hour, dt_init.min, InpStartHour, InpStartMinute, InpEndHour, InpEndMinute);
   Print("{safe_name} inicializado exitosamente en MetaTrader 5.");
   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
{handle_releases_str}
   Print("{safe_name} deinitialized. Reason: ", reason);
}}

//+------------------------------------------------------------------+
//| Checks whether current time is within trading session            |
//+------------------------------------------------------------------+
bool IsWithinTradingHours()
{{
   if(!InpUseTimeFilter) return true;
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   
   // Weekend filter
   if(dt.day_of_week == 0 || dt.day_of_week == 6) return false;
   // Friday close filter
   if(InpFilterFriday && dt.day_of_week == 5 && dt.hour >= 20) return false;

   int cur_min   = dt.hour * 60 + dt.min;
   int start_min = InpStartHour * 60 + InpStartMinute;
   int end_min   = InpEndHour * 60 + InpEndMinute;

   if(start_min <= end_min)
      return (cur_min >= start_min && cur_min <= end_min);
   else
      return (cur_min >= start_min || cur_min <= end_min);
}}

//+------------------------------------------------------------------+
//| Checks spread against maximum allowed threshold                  |
//+------------------------------------------------------------------+
bool IsSpreadAllowed()
{{
   if(InpMaxSpreadPoints <= 0) return true;
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   return (spread <= InpMaxSpreadPoints);
}}

//+------------------------------------------------------------------+
//| Checks whether a new bar has just opened                         |
//+------------------------------------------------------------------+
bool IsNewBar()
{{
   datetime current_bar = iTime(_Symbol, _Period, 0);
   if(current_bar == 0) return false;
   if(current_bar != m_last_bar_time)
   {{
      m_last_bar_time = current_bar;
      return true;
   }}
   return false;
}}

//+------------------------------------------------------------------+
//| Real-time Break-Even and Trailing Stop Manager                   |
//+------------------------------------------------------------------+
void CheckBreakEvenAndTrailing(double pip_size, int digits)
{{
   if(InpBreakEvenPips <= 0 && InpTrailingPips <= 0) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         {{
            double open_price = m_position.PriceOpen();
            double current_sl = m_position.StopLoss();
            double current_tp = m_position.TakeProfit();

            // BUY POSITION
            if(m_position.PositionType() == POSITION_TYPE_BUY)
            {{
               double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               // Break-even: Move SL to entry
               if(InpBreakEvenPips > 0 && (bid - open_price) >= (InpBreakEvenPips * pip_size))
               {{
                  if(current_sl < open_price)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), NormalizeDouble(open_price, digits), current_tp);
                     current_sl = open_price;
                  }}
               }}
               // Trailing stop
               if(InpTrailingPips > 0 && (bid - open_price) > (InpTrailingPips * pip_size))
               {{
                  double new_sl = NormalizeDouble(bid - (InpTrailingPips * pip_size), digits);
                  if(new_sl > current_sl)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), new_sl, current_tp);
                  }}
               }}
            }}
            // SELL POSITION
            else if(m_position.PositionType() == POSITION_TYPE_SELL)
            {{
               double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               // Break-even: Move SL to entry
               if(InpBreakEvenPips > 0 && (open_price - ask) >= (InpBreakEvenPips * pip_size))
               {{
                  if(current_sl == 0 || current_sl > open_price)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), NormalizeDouble(open_price, digits), current_tp);
                     current_sl = open_price;
                  }}
               }}
               // Trailing stop
               if(InpTrailingPips > 0 && (open_price - ask) > (InpTrailingPips * pip_size))
               {{
                  double new_sl = NormalizeDouble(ask + (InpTrailingPips * pip_size), digits);
                  if(current_sl == 0 || new_sl < current_sl)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), new_sl, current_tp);
                  }}
               }}
            }}
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
//| Count active positions for this EA                               |
//+------------------------------------------------------------------+
int CountPositions(int type = -1)
{{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         {{
            if(type == -1 || m_position.PositionType() == (ENUM_POSITION_TYPE)type)
               count++;
         }}
      }}
   }}
   return count;
}}

//+------------------------------------------------------------------+
//| Close positions by type                                          |
//+------------------------------------------------------------------+
void ClosePositions(ENUM_POSITION_TYPE type)
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         {{
            if(m_position.PositionType() == type)
               m_trade.PositionClose(m_position.Ticket());
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{{
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double pip_size = (digits == 3 || digits == 5) ? point * 10 : point;

   // 1. Monitoreo en tiempo real de Break-Even y Trailing Stop
   CheckBreakEvenAndTrailing(pip_size, digits);

   // 2. Filtro de Horarios de Sesion y Filtro de Spread
   if(!IsWithinTradingHours()) return;
   if(!IsSpreadAllowed()) return;

   // 3. Ejecucion de nuevas entradas solo en apertura de nueva vela
   if(!IsNewBar()) return;

   // Update indicator buffer data
{copy_buffers_str}

   // Rates for price reference
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   if(CopyRates(_Symbol, _Period, 1, 3, rates) <= 0) return;

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   // --- Evaluate Signals ---
   bool signal_buy  = ({entry_buy_logic});
   bool signal_sell = ({entry_sell_logic});
   bool exit_buy    = ({exit_buy_logic});
   bool exit_sell   = ({exit_sell_logic});

   // Handle Exits
   if(exit_buy)
      ClosePositions(POSITION_TYPE_BUY);
   if(exit_sell)
      ClosePositions(POSITION_TYPE_SELL);

   // Handle Entries
   int total_positions = CountPositions();

   if(signal_buy && total_positions == 0)
   {{
      double sl = (InpStopLossPips > 0) ? NormalizeDouble(ask - (InpStopLossPips * pip_size), digits) : 0;
      double tp = (InpTakeProfitPips > 0) ? NormalizeDouble(ask + (InpTakeProfitPips * pip_size), digits) : 0;
      m_trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{safe_name}_BUY");
   }}
   else if(signal_sell && total_positions == 0)
   {{
      double sl = (InpStopLossPips > 0) ? NormalizeDouble(bid + (InpStopLossPips * pip_size), digits) : 0;
      double tp = (InpTakeProfitPips > 0) ? NormalizeDouble(bid - (InpTakeProfitPips * pip_size), digits) : 0;
      m_trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{safe_name}_SELL");
   }}
}}
//+------------------------------------------------------------------+
"""
        return mql5_code

    @staticmethod
    def generate_orb_first_candle(strategy_spec: Dict[str, Any]) -> str:
        """Generates dedicated Opening Range Breakout (ORB) / Primera Vela Expert Advisor."""
        name = strategy_spec.get("name", "Frankztrades_PrimeraVela_ORB_EA")
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
        description = strategy_spec.get("description", "Opening Range Breakout de la Primera Vela de 5M en Apertura de New York (1:1 RR)")
        lot_size = strategy_spec.get("default_lot", 0.01)
        magic_number = strategy_spec.get("magic_number", 505101)
        start_hour = strategy_spec.get("start_hour", 15)
        start_min = strategy_spec.get("start_minute", 30)
        max_spread = strategy_spec.get("max_spread_points", 30)
        rr_ratio = strategy_spec.get("risk_reward_ratio_val", 1.0)
        fallback_sl_points = strategy_spec.get("stop_loss_points", 250)

        mql5_code = f"""//+------------------------------------------------------------------+
//|                                     {safe_name}.mq5 |
//|                                  Trading Strategy Studio (AI)    |
//|               Estrategia Primera Vela M5 / ORB Apertura New York |
//+------------------------------------------------------------------+
#property copyright "Trading Strategy Studio"
#property link      "https://github.com/enfoc/trading-strategy-studio"
#property version   "1.00"
#property description "{description}"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>

//--- Input Parameters
input group "=== Configuracion Rango de Primera Vela ==="
input int    InpStartHour          = {start_hour};      // Hora Apertura New York (Hora Servidor MT5)
input int    InpStartMinute        = {start_min};      // Minuto Apertura New York
input int    InpRangeMinutes       = 5;       // Duracion Primera Vela (5 Minutos)
input int    InpMaxWindowMinutes   = 90;      // Ventana Operativa Maxima (90 Minutos)
input bool   InpOneTradePerDay     = true;    // Limite Estricto de 1 Sola Operacion al Dia

input group "=== Gestion de Riesgo y R:R ==="
input double InpLotSize            = {lot_size};    // Lote Operativo
input double InpRiskRewardRatio    = {rr_ratio};     // Ratio Riesgo:Beneficio (1.0 = 1:1)
input int    InpFallbackSLPoints   = {fallback_sl_points};     // Stop Loss de Respaldo (Puntos)
input int    InpMaxSpreadPoints    = {max_spread};     // Spread Maximo Permitido (Puntos)
input ulong  InpMagicNumber        = {magic_number}; // Magic Number
input int    InpSlippage           = 10;      // Slippage Permitido

//--- Objetos Globales
CTrade         m_trade;
CPositionInfo  m_position;
datetime       m_last_bar_time      = 0;
datetime       m_current_day        = 0;
bool           m_traded_today       = false;
bool           m_range_formed       = false;
double         m_range_high         = 0.0;
double         m_range_low          = 0.0;
datetime       m_session_start_time = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{{
   m_trade.SetExpertMagicNumber(InpMagicNumber);
   m_trade.SetDeviationInPoints(InpSlippage);
   m_trade.SetTypeFillingBySymbol(_Symbol);

   MqlDateTime dt_init;
   TimeToStruct(TimeCurrent(), dt_init);
   PrintFormat("Servidor MT5 conectado. Hora actual del servidor: %02d:%02d. Apertura New York configurada: %02d:%02d (Hora Servidor MT5: 8:30 EST = 15:30 Server).",
      dt_init.hour, dt_init.min, InpStartHour, InpStartMinute);
   Print("{safe_name} inicializado correctamente. Monitoreando primera vela de 5M.");
   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   Print("{safe_name} finalizado. Razon: ", reason);
}}

//+------------------------------------------------------------------+
//| Checks whether a new bar has just opened                         |
//+------------------------------------------------------------------+
bool IsNewBar()
{{
   datetime current_bar = iTime(_Symbol, _Period, 0);
   if(current_bar == 0) return false;
   if(current_bar != m_last_bar_time)
   {{
      m_last_bar_time = current_bar;
      return true;
   }}
   return false;
}}

//+------------------------------------------------------------------+
//| Counts active positions for this EA                              |
//+------------------------------------------------------------------+
int CountPositions()
{{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
            count++;
      }}
   }}
   return count;
}}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{{
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);

   // 1. Reset diario al cambiar el dia
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   datetime today = StringToTime(StringFormat("%04d.%02d.%02d 00:00:00", dt.year, dt.mon, dt.day));
   if(today != m_current_day)
   {{
      m_current_day        = today;
      m_traded_today       = false;
      m_range_formed       = false;
      m_range_high         = 0.0;
      m_range_low          = 0.0;
      m_session_start_time = StringToTime(StringFormat("%04d.%02d.%02d %02d:%02d:00", dt.year, dt.mon, dt.day, InpStartHour, InpStartMinute));
   }}

   // 2. Comprobar Spread
   if(InpMaxSpreadPoints > 0)
   {{
      long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
      if(spread > InpMaxSpreadPoints) return;
   }}

   // 3. Evaluar formacion del rango de los primeros 5 minutos (manos quietas)
   datetime current_time = TimeCurrent();
   datetime range_end_time = m_session_start_time + (InpRangeMinutes * 60);
   datetime window_end_time = m_session_start_time + (InpMaxWindowMinutes * 60);

   if(!m_range_formed && current_time >= range_end_time && current_time < window_end_time)
   {{
      int bar_idx = iBarShift(_Symbol, PERIOD_M5, m_session_start_time, true);
      if(bar_idx >= 0)
      {{
         m_range_high = iHigh(_Symbol, PERIOD_M5, bar_idx);
         m_range_low  = iLow(_Symbol, PERIOD_M5, bar_idx);
         if(m_range_high > 0 && m_range_low > 0 && m_range_high > m_range_low)
         {{
            m_range_formed = true;
            PrintFormat("Rango Primera Vela 5M establecido: High=%.5f, Low=%.5f", m_range_high, m_range_low);
         }}
      }}
   }}

   // 4. Ejecucion de entradas solo en nueva vela cerrada
   if(!IsNewBar()) return;
   if(!m_range_formed) return;
   if(current_time >= window_end_time) return;
   if(InpOneTradePerDay && m_traded_today) return;
   if(CountPositions() > 0) return;

   // Obtener precio de cierre de la vela recien cerrada (shift 1)
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   if(CopyRates(_Symbol, _Period, 1, 2, rates) <= 0) return;

   double close_1 = rates[0].close;
   double open_1  = rates[0].open;
   double low_1   = rates[0].low;
   double high_1  = rates[0].high;

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   // SENAL COMPRA: Cierre con cuerpo por encima del High de la primera vela
   if(close_1 > m_range_high && close_1 > open_1)
   {{
      double sl = NormalizeDouble(low_1, digits);
      if((ask - sl) < (InpFallbackSLPoints * point) / 2)
         sl = NormalizeDouble(m_range_low, digits);
      if((ask - sl) <= 0)
         sl = NormalizeDouble(ask - (InpFallbackSLPoints * point), digits);

      double risk_dist = ask - sl;
      double tp = NormalizeDouble(ask + (risk_dist * InpRiskRewardRatio), digits);

      if(m_trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{safe_name}_BUY"))
      {{
         m_traded_today = true;
         PrintFormat("Compra ejecutada por Ruptura de Primera Vela. Ask=%.5f, SL=%.5f, TP=%.5f (1:1)", ask, sl, tp);
      }}
   }}
   // SENAL VENTA: Cierre con cuerpo por debajo del Low de la primera vela
   else if(close_1 < m_range_low && close_1 < open_1)
   {{
      double sl = NormalizeDouble(high_1, digits);
      if((sl - bid) < (InpFallbackSLPoints * point) / 2)
         sl = NormalizeDouble(m_range_high, digits);
      if((sl - bid) <= 0)
         sl = NormalizeDouble(bid + (InpFallbackSLPoints * point), digits);

      double risk_dist = sl - bid;
      double tp = NormalizeDouble(bid - (risk_dist * InpRiskRewardRatio), digits);

      if(m_trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{safe_name}_SELL"))
      {{
         m_traded_today = true;
         PrintFormat("Venta ejecutada por Ruptura de Primera Vela. Bid=%.5f, SL=%.5f, TP=%.5f (1:1)", bid, sl, tp);
      }}
   }}
}}
//+------------------------------------------------------------------+
"""
        return mql5_code
