import re
from typing import Dict, Any

class MQL5Generator:
    """Generates clean, compilable, institutional-grade MQL5 Expert Advisors."""

    @staticmethod
    def generate(strategy_spec: Dict[str, Any]) -> str:
        name = strategy_spec.get("name", "AI_Generated_Strategy")
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', name)
        description = strategy_spec.get("description", "Automated strategy generated by Trading Strategy Studio")
        
        lot_size = strategy_spec.get("default_lot", 0.01)
        sl_points = strategy_spec.get("stop_loss_points", 300)
        tp_points = strategy_spec.get("take_profit_points", 600)
        be_pips = strategy_spec.get("breakeven_pips", 15)
        trailing_pips = strategy_spec.get("trailing_stop_pips", 12)
        magic_number = strategy_spec.get("magic_number", 789101)

        start_hour = strategy_spec.get("start_hour", 13)
        start_min = strategy_spec.get("start_minute", 30)
        end_hour = strategy_spec.get("end_hour", 20)
        end_min = strategy_spec.get("end_minute", 0)
        use_time_filter = strategy_spec.get("use_time_filter", True)
        max_spread = strategy_spec.get("max_spread_points", 35)
        
        indicators = strategy_spec.get("indicators", [])
        entry_buy_logic = strategy_spec.get("entry_buy_code", "false")
        entry_sell_logic = strategy_spec.get("entry_sell_code", "false")
        exit_buy_logic = strategy_spec.get("exit_buy_code", "false")
        exit_sell_logic = strategy_spec.get("exit_sell_code", "false")
        custom_inputs = strategy_spec.get("custom_inputs", [])

        # Build Input variables
        inputs_code = []
        inputs_code.append(f'input group "=== Risk and Order Settings ==="')
        inputs_code.append(f'input double InpLotSize        = {lot_size};       // Lot Size')
        inputs_code.append(f'input int    InpStopLossPips   = {sl_points // 10};       // Stop Loss (Pips)')
        inputs_code.append(f'input int    InpTakeProfitPips = {tp_points // 10};      // Take Profit (Pips)')
        inputs_code.append(f'input int    InpBreakEvenPips  = {be_pips};       // Break-Even Trigger (Pips, 0=Off)')
        inputs_code.append(f'input int    InpTrailingPips   = {trailing_pips};       // Trailing Stop (Pips, 0=Off)')
        inputs_code.append(f'input ulong  InpMagicNumber    = {magic_number};   // Magic Number')
        inputs_code.append(f'input int    InpSlippage       = 10;               // Slippage Points')

        inputs_code.append(f'input group "=== Session and Operating Hours ==="')
        inputs_code.append(f'input bool   InpUseTimeFilter  = {"true" if use_time_filter else "false"};       // Enable Trading Session Filter')
        inputs_code.append(f'input int    InpStartHour      = {start_hour};       // Session Start Hour (Server Time)')
        inputs_code.append(f'input int    InpStartMinute    = {start_min};       // Session Start Minute')
        inputs_code.append(f'input int    InpEndHour        = {end_hour};       // Session End Hour')
        inputs_code.append(f'input int    InpEndMinute      = {end_min};       // Session End Minute')
        inputs_code.append(f'input bool   InpFilterFriday   = true;       // Avoid Friday Late Afternoon Trading')

        inputs_code.append(f'input group "=== Spread and Safety Filter ==="')
        inputs_code.append(f'input int    InpMaxSpreadPoints= {max_spread};       // Max Allowed Spread (Points, 0=Off)')
        
        if custom_inputs:
            inputs_code.append(f'input group "=== Strategy Parameters ==="')
            for inp in custom_inputs:
                inputs_code.append(f"input {inp['type']} {inp['name']} = {inp['default']}; // {inp.get('comment', inp['name'])}")

        # Build indicator handle declarations and init code
        handle_decls = []
        handle_inits = []
        handle_releases = []
        copy_buffers = []

        for ind in indicators:
            h_var = ind["handle_var"]
            b_var = ind["buffer_var"]
            init_call = ind["init_call"]
            
            handle_decls.append(f"int {h_var} = INVALID_HANDLE;")
            handle_decls.append(f"double {b_var}[];")
            
            handle_inits.append(f"   {h_var} = {init_call};")
            handle_inits.append(f"   if({h_var} == INVALID_HANDLE)")
            handle_inits.append(f"   {{\n      Print(\"Error creating indicator {h_var}: \", GetLastError());\n      return INIT_FAILED;\n   }}")
            handle_inits.append(f"   ArraySetAsSeries({b_var}, true);")
            
            handle_releases.append(f"   if({h_var} != INVALID_HANDLE) IndicatorRelease({h_var});")
            
            copy_buffers.append(f"   if(CopyBuffer({h_var}, 0, 1, 3, {b_var}) <= 0) return;")

        inputs_str = "\n".join(inputs_code)
        handle_decls_str = "\n".join(handle_decls)
        handle_inits_str = "\n".join(handle_inits)
        handle_releases_str = "\n".join(handle_releases)
        copy_buffers_str = "\n".join(copy_buffers)

        mql5_code = f"""//+------------------------------------------------------------------+
//|                                     {safe_name}.mq5 |
//|                                  Trading Strategy Studio (AI)    |
//+------------------------------------------------------------------+
#property copyright "Trading Strategy Studio"
#property link      "https://github.com/enfoc/trading-strategy-studio"
#property version   "1.00"
#property description "{description}"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>

//--- Input parameters
{inputs_str}

//--- Global Objects
CTrade         m_trade;
CPositionInfo  m_position;
datetime       m_last_bar_time = 0;

//--- Indicators Handles and Buffers
{handle_decls_str}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{{
   m_trade.SetExpertMagicNumber(InpMagicNumber);
   m_trade.SetDeviationInPoints(InpSlippage);
   m_trade.SetTypeFillingBySymbol(_Symbol);

{handle_inits_str}

   Print("{safe_name} initialized successfully.");
   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
{handle_releases_str}
   Print("{safe_name} deinitialized. Reason: ", reason);
}}

//+------------------------------------------------------------------+
//| Checks whether current time is within trading session            |
//+------------------------------------------------------------------+
bool IsWithinTradingHours()
{{
   if(!InpUseTimeFilter) return true;
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   
   // Weekend filter
   if(dt.day_of_week == 0 || dt.day_of_week == 6) return false;
   // Friday close filter
   if(InpFilterFriday && dt.day_of_week == 5 && dt.hour >= 20) return false;

   int cur_min   = dt.hour * 60 + dt.min;
   int start_min = InpStartHour * 60 + InpStartMinute;
   int end_min   = InpEndHour * 60 + InpEndMinute;

   if(start_min <= end_min)
      return (cur_min >= start_min && cur_min <= end_min);
   else
      return (cur_min >= start_min || cur_min <= end_min);
}}

//+------------------------------------------------------------------+
//| Checks spread against maximum allowed threshold                  |
//+------------------------------------------------------------------+
bool IsSpreadAllowed()
{{
   if(InpMaxSpreadPoints <= 0) return true;
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   return (spread <= InpMaxSpreadPoints);
}}

//+------------------------------------------------------------------+
//| Checks whether a new bar has just opened                         |
//+------------------------------------------------------------------+
bool IsNewBar()
{{
   datetime current_bar = iTime(_Symbol, _Period, 0);
   if(current_bar == 0) return false;
   if(current_bar != m_last_bar_time)
   {{
      m_last_bar_time = current_bar;
      return true;
   }}
   return false;
}}

//+------------------------------------------------------------------+
//| Real-time Break-Even and Trailing Stop Manager                   |
//+------------------------------------------------------------------+
void CheckBreakEvenAndTrailing(double pip_size, int digits)
{{
   if(InpBreakEvenPips <= 0 && InpTrailingPips <= 0) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         {{
            double open_price = m_position.PriceOpen();
            double current_sl = m_position.StopLoss();
            double current_tp = m_position.TakeProfit();

            // BUY POSITION
            if(m_position.PositionType() == POSITION_TYPE_BUY)
            {{
               double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
               // Break-even: Move SL to entry
               if(InpBreakEvenPips > 0 && (bid - open_price) >= (InpBreakEvenPips * pip_size))
               {{
                  if(current_sl < open_price)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), NormalizeDouble(open_price, digits), current_tp);
                     current_sl = open_price;
                  }}
               }}
               // Trailing stop
               if(InpTrailingPips > 0 && (bid - open_price) > (InpTrailingPips * pip_size))
               {{
                  double new_sl = NormalizeDouble(bid - (InpTrailingPips * pip_size), digits);
                  if(new_sl > current_sl)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), new_sl, current_tp);
                  }}
               }}
            }}
            // SELL POSITION
            else if(m_position.PositionType() == POSITION_TYPE_SELL)
            {{
               double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
               // Break-even: Move SL to entry
               if(InpBreakEvenPips > 0 && (open_price - ask) >= (InpBreakEvenPips * pip_size))
               {{
                  if(current_sl == 0 || current_sl > open_price)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), NormalizeDouble(open_price, digits), current_tp);
                     current_sl = open_price;
                  }}
               }}
               // Trailing stop
               if(InpTrailingPips > 0 && (open_price - ask) > (InpTrailingPips * pip_size))
               {{
                  double new_sl = NormalizeDouble(ask + (InpTrailingPips * pip_size), digits);
                  if(current_sl == 0 || new_sl < current_sl)
                  {{
                     m_trade.PositionModify(m_position.Ticket(), new_sl, current_tp);
                  }}
               }}
            }}
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
//| Count active positions for this EA                               |
//+------------------------------------------------------------------+
int CountPositions(int type = -1)
{{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         {{
            if(type == -1 || m_position.PositionType() == (ENUM_POSITION_TYPE)type)
               count++;
         }}
      }}
   }}
   return count;
}}

//+------------------------------------------------------------------+
//| Close positions by type                                          |
//+------------------------------------------------------------------+
void ClosePositions(ENUM_POSITION_TYPE type)
{{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {{
      if(m_position.SelectByIndex(i))
      {{
         if(m_position.Symbol() == _Symbol && m_position.Magic() == InpMagicNumber)
         {{
            if(m_position.PositionType() == type)
               m_trade.PositionClose(m_position.Ticket());
         }}
      }}
   }}
}}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{{
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   double pip_size = (digits == 3 || digits == 5) ? point * 10 : point;

   // 1. Monitoreo en tiempo real de Break-Even y Trailing Stop
   CheckBreakEvenAndTrailing(pip_size, digits);

   // 2. Filtro de Horarios de Sesion y Filtro de Spread
   if(!IsWithinTradingHours()) return;
   if(!IsSpreadAllowed()) return;

   // 3. Ejecucion de nuevas entradas solo en apertura de nueva vela
   if(!IsNewBar()) return;

   // Update indicator buffer data
{copy_buffers_str}

   // Rates for price reference
   MqlRates rates[];
   ArraySetAsSeries(rates, true);
   if(CopyRates(_Symbol, _Period, 1, 3, rates) <= 0) return;

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   // --- Evaluate Signals ---
   bool signal_buy  = ({entry_buy_logic});
   bool signal_sell = ({entry_sell_logic});
   bool exit_buy    = ({exit_buy_logic});
   bool exit_sell   = ({exit_sell_logic});

   // Handle Exits
   if(exit_buy)
      ClosePositions(POSITION_TYPE_BUY);
   if(exit_sell)
      ClosePositions(POSITION_TYPE_SELL);

   // Handle Entries
   int total_positions = CountPositions();

   if(signal_buy && total_positions == 0)
   {{
      double sl = (InpStopLossPips > 0) ? NormalizeDouble(ask - (InpStopLossPips * pip_size), digits) : 0;
      double tp = (InpTakeProfitPips > 0) ? NormalizeDouble(ask + (InpTakeProfitPips * pip_size), digits) : 0;
      m_trade.Buy(InpLotSize, _Symbol, ask, sl, tp, "{safe_name}_BUY");
   }}
   else if(signal_sell && total_positions == 0)
   {{
      double sl = (InpStopLossPips > 0) ? NormalizeDouble(bid + (InpStopLossPips * pip_size), digits) : 0;
      double tp = (InpTakeProfitPips > 0) ? NormalizeDouble(bid - (InpTakeProfitPips * pip_size), digits) : 0;
      m_trade.Sell(InpLotSize, _Symbol, bid, sl, tp, "{safe_name}_SELL");
   }}
}}
//+------------------------------------------------------------------+
"""
        return mql5_code
